---
# optional if you provide outside mysql
- hosts: mysql
  become: yes
  roles:
    - rancher-mysql
- hosts: server
  become: yes
  roles:
    - rancher-server
- hosts: agent
  become: yes
  roles:
    - rancher-agent
