---
- name: configure rancher mysql server
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - src: rancher-mysql.service.j2
      dest: /usr/lib/systemd/system/rancher-mysql.service
    - src: rancher-mysql.env.j2
      dest: /etc/default/rancher-mysql.env
  notify:
    - reload rancher-mysql
    - restart rancher-mysql
  tags:
    - rancher-server
